In [230]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import langevin
from scipy.stats import pearsonr
from scipy.optimize import root

SMALL_SIZE = 16
MEDIUM_SIZE = 18
BIGGER_SIZE = 20

plt.rc('font', size=SMALL_SIZE)          # controls default text sizes
plt.rc('axes', titlesize=SMALL_SIZE)     # fontsize of the axes title
plt.rc('axes', labelsize=MEDIUM_SIZE)    # fontsize of the x and y labels
plt.rc('xtick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('ytick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('legend', fontsize=SMALL_SIZE)    # legend fontsize
plt.rc('figure', titlesize=BIGGER_SIZE)  # fontsize of the figure title

#SEED = 35010732 # from random.org
#np.random.seed(SEED)

print(plt.style.available)
plt.style.use('seaborn-white')

['seaborn-dark', 'seaborn-darkgrid', 'seaborn-ticks', 'fivethirtyeight', 'seaborn-whitegrid', 'classic', '_classic_test', 'fast', 'seaborn-talk', 'seaborn-dark-palette', 'seaborn-bright', 'seaborn-pastel', 'grayscale', 'seaborn-notebook', 'ggplot', 'seaborn-colorblind', 'seaborn-muted', 'seaborn', 'Solarize_Light2', 'seaborn-paper', 'bmh', 'tableau-colorblind10', 'seaborn-white', 'dark_background', 'seaborn-poster', 'seaborn-deep']


In [231]:
def correlated_ts(c,delta_t = 0.1,N=1000):
    # parameters for coupled oscillator
    K,D = 1.0,1.0
    data1 = langevin.time_series(A=1/K, D=D, delta_t=delta_t, N=N)
    data2 = langevin.time_series(A=1/(K+np.abs(c)), D=D, delta_t=delta_t, N=N)
    x1 = (data1 + data2)/2
    if c>0:
        x2 = (data1 - data2)/2
    else:
        x2 = (data2-data1)/2

    return x1,x2

def c_rho(rho):
    return 2*np.abs(rho)/(1-np.abs(rho))*np.sign(rho)


In [232]:
N = 1000
delta_t = 0.3
rho = 0.5
print("N: ",N,"delta t: ",delta_t,"rho: ",rho)

x1,x2 = correlated_ts(c_rho(rho),delta_t=delta_t,N=N)
print("Pearson r,p: ",pearsonr(x1,x2))
print(x1.std()**2,x2.std()**2)

N:  1000 delta t:  0.3 rho:  0.5
Pearson r,p:  (0.4929269165429059, 2.4187146602917064e-62)
0.3102517238517878 0.32035160338809177


In [233]:
def calc_fundstats(x):
    return x[0]**2+x[-1]**2,np.sum(x[1:-1]**2),np.sum(x[0:-1]*x[1:])

In [234]:
def b(D,A,delta_t):
    return np.exp(-D/A*delta_t)

def q(aep,ass,ac,b):
    return (aep + (1+b**2)*ass - 2*b*ac)/(1-b**2)

def dqdB(aep,ass,ac,b):
    return 2*(b*aep+2*b*ass-(1+b**2)*ac)/(1-b**2)**2

def d2qdB2(aep,ass,ac,b):
    return (6*b+2)/(1-b**2)**3*(aep+2*ass)-(4*b**3+12*b)/(1-b**2)**3*ac

def dBdA(b,D,A,delta_t):
    return b*D*delta_t/A**2

def dBdD(b,A,delta_t):
    return -b*delta_t/A

def d2BdA2(b,D,A,delta_t):
    return b*D*delta_t/A**3*(D*delta_t/A-2)

def d2BdD2(b,A,delta_t):
    return b*delta_t**2/A**2

def d2BdAdD(b,D,A,delta_t):
    return b*delta_t/A**2*(1-D*delta_t/A)

def d2qdD2(aep,ass,ac,b,A,delta_t):
    return d2qdB2(aep,ass,ac,b)*dBdD(b,A,delta_t)**2+dqdB(aep,ass,ac,b)*d2BdD2(b,A,delta_t)

def d2qdA2(aep,ass,ac,b,D,A,delta_t):
    return d2qdB2(aep,ass,ac,b)*dBdA(b,D,A,delta_t)**2+dqdB(aep,ass,ac,b)*d2BdA2(b,D,A,delta_t)

def d2qdAdD(aep,ass,ac,b,D,A,delta_t):
    return d2qdB2(aep,ass,ac,b)*dBdA(b,D,A,delta_t)*dBdD(b,A,delta_t)+dqdB(aep,ass,ac,b)*d2BdAdD(b,D,A,delta_t)

def d2PdA2(N,aep,ass,ac,b,D,A,delta_t):
    return (N/2/A**2 - 
            q(aep,ass,ac,b)/A**3 +
            (N-1)/(1-b**2)*(b*d2BdA2(b,D,A,delta_t) + dBdA(b,D,A,delta_t)**2*(1+b**2)/(1-b**2)) -
            d2qdA2(aep,ass,ac,b,D,A,delta_t)/2/A)
        
def d2PdAdD(N,aep,ass,ac,b,D,A,delta_t):
    return (dqdB(aep,ass,ac,b)*dBdD(b,A,delta_t)/2/A**2 -
            d2qdAdD(aep,ass,ac,b,D,A,delta_t)/2/A +
            (N-1)/(1-b**2)*(b*d2BdAdD(b,D,A,delta_t) + dBdA(b,D,A,delta_t)*dBdD(b,A,delta_t)*(1+b**2)/(1-b**2)))

def d2PdD2(N,a1ep,a1ss,a1c,a2ep,a2ss,a2c,b1,b2,D,A1,A2,delta_t):
    return ((N-1)/(1-b1**2)*(b1*d2BdD2(b1,A1,delta_t) + dBdD(b1,A1,delta_t)**2*(1+b1**2)/(1-b1**2))+
           (N-1)/(1-b2**2)*(b2*d2BdD2(b2,A2,delta_t) + dBdD(b2,A2,delta_t)**2*(1+b2**2)/(1-b2**2))-
           d2qdD2(a1ep,a1ss,a1c,b1,A1,delta_t)/2/A1 -
           d2qdD2(a2ep,a2ss,a2c,b2,A2,delta_t)/2/A2)
           
def phi_deriv(x,a1ep,a1ss,a1c,a2ep,a2ss,a2c,delta_t,N):
    # x[0] = A1, x[1] = A2, x[2]=D
    A1 = x[0]
    A2 = x[1]
    D = x[2]
    b1 = b(D,A1,delta_t)
    b2 = b(D,A2,delta_t)
    Q1 = q(a1ep,a1ss,a1c,b1)
    Q2 = q(a2ep,a2ss,a2c,b2)
    dQ1 = dqdB(a1ep,a1ss,a1c,b1)
    dQ2 = dqdB(a2ep,a2ss,a2c,b2)
    y1 = -N*A1**2/2 + A1*Q1/2 + b1*D*delta_t*(A1*b1*(N-1)/(1-b1**2)-dQ1/2)
    y2 = -N*A2**2/2 + A2*Q2/2 + b2*D*delta_t*(A2*b2*(N-1)/(1-b2**2)-dQ2/2)
    y3 = (b1*(N-1)/(1-b1**2)-dQ1/A1/2)*b1/A1 + (b2*(N-1)/(1-b2**2)-dQ2/A2/2)*b2/A2
    return np.array([y1,y2,y3])

In [235]:
def d2PdA2N(N,b,A,delta_t):
    return -N/2/A - N/(1-b**2)**2*dBdA(b,D,A,delta_t)**2*(1+b**2+6*b/(1+b))

def d2PdAdDN(N,b,D,A,delta_t):
    return N*b/(1-b**2)*dBdD(b,A,delta_t) - N/(1-b**2)**2*dBdA(b,D,A,delta_t)*dBdD(b,A,delta_t)*(1+b**2+6*b/(1+b))

def d2PdD2N(N,b1,b2,D,A1,A2,delta_t):
    return (-N/(1-b1**2)**2*dBdD(b1,A1,delta_t)**2*(1+b1**2+6*b1/(1+b1))-
            N/(1-b2**2)**2*dBdD(b2,A2,delta_t)**2*(1+b2**2+6*b2/(1+b2)))

In [236]:
para = calc_fundstats(x1+x2) + calc_fundstats(x1-x2) +(delta_t,N)
para

(6.605239114246895,
 935.326004368374,
 680.8314611449022,
 0.7599070807485191,
 319.9984843555729,
 129.87999203247017,
 0.3,
 1000)

In [237]:
guessa1 = (x1+x2).std()**2
guessa2 = (x1-x2).std()**2
guessd = 0.5
c_guess = (guessa1-guessa2)/guessa2
print(guessa1,guessa2,guessd,c_guess/(2+c_guess))
result = root(phi_deriv, [guessa1,guessa2,guessd],args=para)
print(result.x)
#print(phi_deriv(result.x,*para))
#print(phi_deriv([guessa1,guessa2,guessd],*para))
A1 = result.x[0]
A2 = result.x[1]
D = result.x[2]

0.9414048099536099 0.31980184452614946 0.5 0.49286368987948936
[0.94622229 0.32182729 0.99090163]


In [238]:
c_max = (result.x[0]-result.x[1])/result.x[1]
rho_max = c_max/(2+c_max)
print(c_max,rho_max)

1.9401555884183797 0.4924058314146875


In [239]:
# lets calculate the Jacobian
b1 = b(D,A1,delta_t)
b2 = b(D,A2,delta_t)
a1ep,a1ss,a1c = calc_fundstats(x1+x2)
a2ep,a2ss,a2c = calc_fundstats(x1-x2)
d2PdA2_1m = d2PdA2(N,a1ep,a1ss,a1c,b1,D,A1,delta_t)
d2PdA2_2m = d2PdA2(N,a2ep,a2ss,a2c,b2,D,A2,delta_t)
d2PdD2m = d2PdD2(N,a1ep,a1ss,a1c,a2ep,a2ss,a2c,b1,b2,D,A1,A2,delta_t)
d2PdAdD_1m = d2PdAdD(N,a1ep,a1ss,a1c,b1,D,A1,delta_t)
d2PdAdD_2m = d2PdAdD(N,a2ep,a2ss,a2c,b2,D,A2,delta_t)

In [240]:
hessian = np.array([[d2PdA2_1m,0,d2PdAdD_1m],[0,d2PdA2_2m,d2PdAdD_2m],[d2PdAdD_1m,d2PdAdD_2m,d2PdD2m]])
hessian

array([[-1662.37791334,     0.        ,   659.47528081],
       [    0.        , -9941.3207248 ,  1154.3027933 ],
       [  659.47528081,  1154.3027933 , -1546.0432258 ]])

In [241]:
var = -np.linalg.inv(hessian)
var

array([[7.38349039e-04, 4.00402246e-05, 3.44842547e-04],
       [4.00402246e-05, 1.12309603e-04, 1.00931736e-04],
       [3.44842547e-04, 1.00931736e-04, 8.69264777e-04]])

In [242]:
print(np.sqrt(var[0,0]))
print(np.sqrt(var[1,1]))
print(np.sqrt(var[2,2]))

0.027172578811905147
0.010597622521531912
0.029483296579821388


In [243]:
d2PdA2_1mN = d2PdA2N(N,b1,A1,delta_t)
d2PdA2_2mN = d2PdA2N(N,b2,A2,delta_t)
d2PdD2mN = d2PdD2N(N,b1,b2,D,A1,A2,delta_t)
d2PdAdD_1mN = d2PdAdDN(N,b1,D,A1,delta_t)
d2PdAdD_2mN = d2PdAdDN(N,b2,D,A2,delta_t)

In [244]:
hessian2 = np.array([[d2PdA2_1mN,0,d2PdAdD_1mN],[0,d2PdA2_2mN,d2PdAdD_2mN],[d2PdAdD_1mN,d2PdAdD_2mN,d2PdD2mN]])
hessian2

array([[-1627.13710156,     0.        ,   686.62055323],
       [    0.        , -6793.44517403,  1527.34085529],
       [  686.62055323,  1527.34085529, -1554.58651463]])

In [245]:
var2 = -np.linalg.inv(hessian2)
var2

array([[0.00080782, 0.00010296, 0.00045795],
       [0.00010296, 0.00020206, 0.00024399],
       [0.00045795, 0.00024399, 0.00108523]])

In [246]:
print(np.sqrt(var2[0,0]))
print(np.sqrt(var2[1,1]))
print(np.sqrt(var2[2,2]))

0.0284222011471951
0.014214625419704667
0.03294288703087906
